# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Get Da submodules
      run: git submodule init && git submodule update
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish osx
      run: dotnet publish LearningMono -r osx-arm64 -p:PublishSingleFile=true --self-contained
    - name: Publish win
      run: dotnet publish LearningMono -r win-x64 -p:PublishSingleFile=true --self-contained
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact
        path: /home/runner/work/Send/Send/LearningMono/bin/Debug/net6.0/osx-arm64/publish/
    - name: Upload Build Artifact windows
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact
        path: /home/runner/work/Send/Send/LearningMono/bin/Debug/net6.0/win-x64/publish/
    - name: Test
      run: dotnet test --no-build --verbosity normal
