# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Get Da submodules
      run: git submodule init && git submodule update
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish osx
      run: dotnet publish -r osx-arm64 --self-contained
    - name: Publish win
      run: dotnet publish -r win-x64 --self-contained
    - name: Test
      run: dotnet test --no-build --verbosity normal
